/* tslint:disable */
/* eslint-disable */
/**
 * Todo.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TodoItemDto
 */
export interface TodoItemDto {
    /**
     * 
     * @type {number}
     * @memberof TodoItemDto
     */
    todoItemId?: number;
    /**
     * 
     * @type {number}
     * @memberof TodoItemDto
     */
    todoListId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TodoItemDto
     */
    title?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TodoItemDto
     */
    done?: boolean;
}
