/* tslint:disable */
/* eslint-disable */
/**
 * Todo.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TodoItemDto } from './todo-item-dto';
/**
 * 
 * @export
 * @interface TodoItemDtoPaginatedList
 */
export interface TodoItemDtoPaginatedList {
    /**
     * 
     * @type {Array<TodoItemDto>}
     * @memberof TodoItemDtoPaginatedList
     */
    items?: Array<TodoItemDto> | null;
    /**
     * 
     * @type {number}
     * @memberof TodoItemDtoPaginatedList
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof TodoItemDtoPaginatedList
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof TodoItemDtoPaginatedList
     */
    totalCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TodoItemDtoPaginatedList
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TodoItemDtoPaginatedList
     */
    hasNextPage?: boolean;
}
