/* tslint:disable */
/* eslint-disable */
/**
 * Todo.Web
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdateTodoItemCommand
 */
export interface UpdateTodoItemCommand {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateTodoItemCommand
     */
    done?: boolean;
}
