import { Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import TodoList from '../components/todos/todoList'

const Todos: NextPage = () => {
  return (
    <>
    {/* //   <Head>
    //     <title>About</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head> */}

      <Typography variant='h2'>Todo List</Typography>
      <TodoList />
    </>
  )
}

export default Todos
